---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:bosh-elastic-stack/elastalert-boshrelease.git
    branch: master
    private_key: ((github-private-key))
    ignore_paths:
    - ci/*
    # - manifest/*
    - README.md
- name: repo-version
  type: semver
  source:
    uri: git@github.com:bosh-elastic-stack/elastalert-boshrelease.git
    branch: version
    private_key: ((github-private-key))
    file: version
    driver: git
- name: gh-release
  type: github-release
  source:
    user: bosh-elastic-stack
    repository: elastalert-boshrelease
    access_token: ((github-access-token))

jobs:
- name: bosh-deploy-dev-in-docker
  serial: true
  plan:
  - aggregate:
    - get: repo
      # trigger: true
  - task: bosh-create-release
    config:
      <<: *BOSH_CREATE_RELEASE
- name: bosh-deploy-dev-in-exsiting-env
  serial: true
  plan:
  - aggregate:
    - get: repo
      trigger: true
  - task: bosh-create-release
    config:
      <<: *BOSH_CREATE_RELEASE
- name: ship-it
  serial: true
  plan:
  - aggregate:
    - get: repo
      # passed:
      # - bosh-deploy-dev-in-exsiting-env
      # - bosh-deploy-dev-in-docker
    - get: repo-version
  - task: create-release
    params:
      <<: *BOSH
      GIT_EMAIL: ((git-email))
      GIT_NAME: ((git-name))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfnorm/rootfs
          tag: 1.0.20
      inputs:
      - name: repo
      - name: repo-version
      outputs:
      - name: releases
      - name: updated-repo
      caches:
      - path: downloads
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          cd downloads
          if [ ! -f ./bosh ];then
            curl -Lo ./bosh https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-3.0.1-linux-amd64
          fi
          cd -
          install ./downloads/bosh /usr/local/bin/bosh
          cd repo
          shopt -s dotglob
          cp -r ./* ../updated-repo
          VERSION=`cat ../repo-version/number`
          TARBALL=elastalert-boshrelease-${VERSION}.tgz
          mkdir -p src
          # curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          # python get-pip.py
          ./add-blobs.sh
          bosh create-release --force --version=${VERSION} --final --tarball=../releases/${TARBALL}
          SHA1=`sha1sum ../releases/${TARBALL} | awk '{print $1}'`
          mkdir -p .sha1
          echo ${SHA1} > .sha1/${VERSION}
          cp -r ./* ../updated-repo
          cd ../updated-repo
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"
          git add -A
          git commit -m "Release ${VERSION}"
          # Release Note
          cat <<EOF > ../releases/note.md
          ## Deployment
          \`\`\` yaml
          # manifest.yml
          ---
          name: elastalert
          releases:
          - name: elastalert
            version: ${VERSION}
            url: https://github.com/making/elastalert-boshrelease/releases/download/${VERSION}/${TARBALL}
            sha1: ${SHA1}
          \`\`\`
          EOF
  - put: repo
    params:
      repository: updated-repo
      tag: repo-version/number
  - put: gh-release
    params:
      name: repo-version/number
      tag: repo-version/number
      body: releases/note.md
      globs:
      - releases/*.tgz

########################################

- name: bump-to-next-patch-version
  plan:
  - aggregate:
    - get: repo
      trigger: true
      passed:
      - ship-it
    - get: repo-version
      params:
        bump: patch
  - put: repo-version
    params:
      file: repo-version/number

- name: bump-to-next-minor-version
  plan:
  - aggregate:
    - get: repo-version
      params:
        bump: minor
  - put: repo-version
    params:
      file: repo-version/number

- name: bump-to-next-majar-version
  plan:
  - aggregate:
    - get: repo-version
      params:
        bump: majar
  - put: repo-version
    params:
      file: repo-version/number

params:
  bosh: &BOSH
    BOSH_CLIENT: ((bosh-client))
    BOSH_ENVIRONMENT: ((bosh-environment))
    BOSH_CLIENT_SECRET: ((bosh-client-secret))
    BOSH_CA_CERT: ((bosh-ca-cert))
tasks: 
  bosh-create-release: &BOSH_CREATE_RELEASE
    platform: linux
    image_resource:
      type: docker-image
      source:
          repository: pcfnorm/rootfs
          tag: 1.0.20
    inputs:
    - name: repo
    outputs:
    - name: releases
    caches:
    - path: downloads
    run:
      path: bash
      args: 
      - -c
      - |
        set -e
        cd downloads
        if [ ! -f ./bosh ];then
          curl -Lo ./bosh https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-3.0.1-linux-amd64
        fi
        cd -
        install ./downloads/bosh /usr/local/bin/bosh
        cd repo
        # curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        # python get-pip.py
        ./add-blobs.sh
        mkdir -p src
        bosh create-release --name=elastalert-dev --force --timestamp-version --tarball=../releases/elastalert-boshrelease.tgz